import Head from "next/head";
import Navbar from "components/Navbar";
import ListItem from "components/list-item";
import Footer from "components/footer";

export default ({children}) => {
  return (
    <>
    <div className="max-w-[1480px] mx-auto px-6 md:px-16">
      <Head>
        <title>Zoloo's blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
    </div>
    <Footer />
    </>
  );
};
