import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div className='max-w-[1480px] mx-auto px-6 md:px-16'>
      <Head>
        <title>Zoloo's blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
       <h2 className='text-red-600 font-semibold text-2xl'>Миний Блог</h2>
      </main>
    </div>
  )
}
