import Head from "next/head";
import Image from "next/image";
import Navbar from "components/Navbar";
import Intro from "components/intro";
import ListItem from "components/list-item";
import GridItem from "components/grid-item";
import { demon, hero, boruto } from "public";

export default function Home() {
  return (
    <div className="max-w-[1480px] mx-auto px-6 md:px-16">
      <Head>
        <title>Zoloo's blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Intro />
      <ListItem />
      <div className="flex flex-wrap gap-6 pb-10 justify-center">
        <GridItem
          author="Б.Золжаргал"
          date="2023 оны 1-р сарын 11"
          img={hero}
          title="My Hero Academia"
          content="Boku no Hero Academia"
        />
        <GridItem
          author="Б.Золжаргал"
          date="2023 оны 1-р сарын 11"
          img={demon}
          title="Kimetsu no yaiba"
          content="Чөтгөрийн ангууч"
        />
        <GridItem
          author="Б.Золжаргал"
          date="2023 оны 1-р сарын 11"
          img={boruto}
          title="Boruto"
          content="Боруто"
        />
      </div>
    </div>
  );
}
